### ISSUE TITLE
m5copy breaks if reply > 1024 bytes

### ISSUE THREAD

**Issue by haavee** [jive-vlbi/jive5ab#18]
Due to the socket layer not reading more than 1024 bytes as reply, sometimes a reply was cut off, leading to parse errors on the reply. Reported by Ruben:

```
SRC::VBS [127.0.0.1:<redacted>] q21326*  ===>  DST::FILE [<redacted>:<controlIP>] /data/q21326/ns/ 
[Errno 2] No such file or directory: '/mnt/dis' 
```

With logging enabled found the following
Server sent this:
```
2021-11-22 08:44:46.70: Reply: !set_disks?  0 : 72 : /mnt/disk01 : /mnt/disk02 : /mnt/disk03 : /mnt/disk04 : /mnt/disk05 : /mnt/disk06 : /mnt/disk07 : /mnt/disk08 : /mnt/disk09 : /mnt/disk10 : /mnt/disk11 : /mnt/disk12 : /mnt/disk13 : /mnt/disk14 : /mnt/disk15 : /mnt/disk16 : /mnt/disk17 : /mnt/disk18 : /mnt/disk19 : /mnt/disk20 : /mnt/disk21 : /mnt/disk22 : /mnt/disk23 : /mnt/disk24 : /mnt/disk25 : /mnt/disk26 : /mnt/disk27 : /mnt/disk28 : /mnt/disk29 : /mnt/disk30 : /mnt/disk31 : /mnt/disk32 : 
/mnt/disk33 : /mnt/disk34 : /mnt/disk35 : /mnt/disk36 : /mnt/disk37 : /mnt/disk38 : /mnt/disk39 : /mnt/disk40 : /mnt/disk41 : /mnt/disk42 : /mnt/disk43 : /mnt/disk44 : /mnt/disk45 : /mnt/disk46 : /mnt/disk47 : /mnt/disk48 : /mnt/disk49 : /mnt/disk50 : /mnt/disk51 : /mnt/disk52 : /mnt/disk53 : /mnt/disk54 : /mnt/disk55 : /mnt/disk56 : /mnt/disk57 : /mnt/disk58 : /mnt/disk59 : 
/mnt/disk60 : /mnt/disk61 : /mnt/disk62 : /mnt/disk63 : /mnt/disk64 : /mnt/disk65 : /mnt/disk66 : /mnt/disk67 : /mnt/disk68 : 
/mnt/disk69 : /mnt/disk70 : /mnt/disk71 : /mnt/disk72 ; 
```

whilst `m5copy` "received" this:

```
2021-11-23 09:12:26.330139 ('127.0.0.1', <redacted>) Reply: !set_disks?  0 : 72 : /mnt/disk01 : /mnt/disk02 : /mnt/disk03 : /mnt/disk04 : /mnt/disk05 : /mnt/disk06 : /mnt/disk07 : /mnt/disk08 : /mnt/disk09 : /mnt/disk10 : /mnt/disk11 : /mnt/disk12 : /mnt/disk13 : /mnt/disk14 : /mnt/disk15 : /mnt/disk16 : /mnt/disk17 : /mnt/disk18 : /mnt/disk19 : /mnt/disk20 : /mnt/disk21 : /mnt/disk22 : /mnt/disk23 : /mnt/disk24 : /mnt/disk25 : /mnt/disk26 : /mnt/disk27 : /mnt/disk28 : /mnt/disk29 : /mnt/disk30 : 
/mnt/disk31 : /mnt/disk32 : /mnt/disk33 : /mnt/disk34 : /mnt/disk35 : /mnt/disk36 : /mnt/disk37 : /mnt/disk38 : /mnt/disk39 : /mnt/disk40 : /mnt/disk41 : /mnt/disk42 : /mnt/disk43 : /mnt/disk44 : /mnt/disk45 : /mnt/disk46 : /mnt/disk47 : /mnt/disk48 : /mnt/disk49 : /mnt/disk50 : /mnt/disk51 : /mnt/disk52 : /mnt/disk53 : /mnt/disk54 : /mnt/disk55: /mnt/disk56 : /mnt/disk57 : 
/mnt/disk58 : /mnt/disk59 : /mnt/disk60 : /mnt/disk61 : /mnt/disk62 : /mnt/disk63 : /mnt/disk64 : /mnt/disk65 : /mnt/disk66 : 
/mnt/disk67 : /mnt/disk68 : /mnt/disk69 : /mnt/disk70 : /mnt/disk71 : /mnt/dis
Traceback (most recent call last): 
 File "/usr/local/bin/m5copy", line 4608, in <module> 
   with xfer_context(src, dst) as xfer: 
 File "/usr/local/bin/m5copy", line 4178, in __enter__ 
   self.dataSource = self.stype(self.srcLocation) 
 File "/usr/local/bin/m5copy", line 2226, in __init__ 
   filter(isRecording, os.listdir(d))), disks), 
 File "/usr/local/bin/m5copy", line 2226, in <lambda> 
   filter(isRecording, os.listdir(d))), disks), 
OSError: [Errno 2] No such file or directory: '/mnt/dis' 
```

**Comment by haavee** [comment]
Fixed in m5copy-v1.61 (see tags)
