### ISSUE TITLE
Python scripts do not work with Python 3

### ISSUE THREAD

**Issue by jaatroko** [jive-vlbi/jive5ab#20]
The Python scripts (though our main concern is m5copy) do not work with Python 3. This is fast approaching showstopper status, as Python 2 has been end-of-life since 2020 and newer operating systems (e.g. Debian 11 "Bullseye") do not (effectively) have it packaged anymore.

**Comment by haavee** [comment]
If you would be kind enough to check that branch out and report any failures (i.e. act as a tester), that would be _great_

**Comment by jaatroko** [comment]
Well, we didn't get very far:
```
oper@watt:~/jive5ab-git/scripts$ ./m5copy vbs://:2620/gk053_mh_no0086* vbs://193.166.42.23/ -udt -p 2630 -r 1000M --resume
$Id: m5copy,v 1.61 2021/24/12 20:23:00 verkout Exp $
    copy VLBI data from somewhere to elsewhere
               (c) H. Verkouter

SRC::VBS [127.0.0.1:2620] gk053_mh_no0086*  ===>  DST::VBS [193.166.42.23:2620:<controlIP>] 
argument should be integer or bytes-like object, not 'str'
oper@watt:~/jive5ab-git/scripts$
```
Looks like byte-string vs. unicode-string troubles, which are apparently common when porting from Python 2 to Python 3. Also, I ran pyflakes3 on m5copy and it produced the following:
```
m5copy:5:1 'math' imported but unused
m5copy:143:24 undefined name 'raw_input'
m5copy:231:17 local variable 'curIF' is assigned to but never used
m5copy:1566:32 '...'.format(...) has unused arguments at position(s): 1
m5copy:2027:56 undefined name 'long'
m5copy:2067:28 undefined name 'xrange'
m5copy:2069:24 undefined name 'xrange'
m5copy:2693:13 local variable 'reply' is assigned to but never used
m5copy:2850:25 '...'.format(...) is missing argument(s) for placeholder(s): 1, 2
m5copy:3075:25 '...'.format(...) has unused arguments at position(s): 1
m5copy:3272:25 '...'.format(...) has unused arguments at position(s): 1
m5copy:3490:9 local variable 'reply' is assigned to but never used
m5copy:3617:25 '...'.format(...) has unused arguments at position(s): 2
m5copy:3661:13 local variable 'reply' is assigned to but never used
m5copy:3919:21 '...'.format(...) has unused arguments at position(s): 0
m5copy:3919:21 '...'.format(...) is missing argument(s) for placeholder(s): 1
m5copy:4055:9 local variable 'mark6' is assigned to but never used
m5copy:4071:13 local variable 'reply' is assigned to but never used
```
of which the "undefined name" ones are probably fatal.

**Comment by jaatroko** [comment]
As a side note/question, vbs_ls/vbs_rm and dbbc_proxy are also Python2-only, any news on those?

**Comment by haavee** [comment]
Hi Juha, please update (pull) your `3.1.0-branch`; this commit https://github.com/jive-vlbi/jive5ab/commit/a896b866809a498afdfdce0f2dff64da54410c27 should fix your issues. I hope I have not missed any more. Thanks for your comments & testing!

**Comment by haavee** [comment]
As to your other question: the `vbs_ls, vbs_rm, vbs_fs` tools are in a different repository and I've created an issue for your request: https://code.jive.eu/verkout/vbs_fs/issues/1
`dbbc_proxy` is not hosted anywhere at the moment but that could do with a python3 overhaul as well, thanks!

**Comment by jaatroko** [comment]
Now it seems to work for a single scan. But for multiple scans we get:
```
oper@watt:~$ /home/oper/jive5ab-git/scripts/m5copy vbs://:2620/gk053_mh_no008* vbs://193.166.42.23/ -udt -p 2630 -r 1000M --resume -d
$Id: m5copy,v 1.61 2021/24/12 20:23:00 verkout Exp $
    copy VLBI data from somewhere to elsewhere
               (c) H. Verkouter

SRC::VBS [127.0.0.1:2620] gk053_mh_no008*  ===>  DST::VBS [193.166.42.23:2620:<controlIP>]
2022-03-10 14:11:55.189873 ('127.0.0.1', 2620) Qry: version?
2022-03-10 14:11:55.200315 ('127.0.0.1', 2620) Reply: !version?  0 :  jive5ab : 2.8.1 : 64bit : release : watt : 21-Sep-2017 : 15h39m55s : nossapi ;
2022-03-10 14:11:55.200503 ('127.0.0.1', 2620) Qry: dts_id?
2022-03-10 14:11:55.211034 ('127.0.0.1', 2620) Reply: !dts_id? 0 : - : 21-Sep-2017 15h39m55s : 1 : watt : 0 : 0 : -  : - : -  ;
2022-03-10 14:11:55.211106 ('127.0.0.1', 2620) Qry: runtime?
2022-03-10 14:11:55.221542 ('127.0.0.1', 2620) Reply: !runtime? 0 : default : 1 ;
2022-03-10 14:11:55.221603 ('127.0.0.1', 2620) Qry: runtime=FItlpPB9:transient
2022-03-10 14:11:55.236048 ('127.0.0.1', 2620) Reply: !runtime = 0 : FItlpPB9 ;
2022-03-10 14:11:55.236131 ('127.0.0.1', 2620) Qry: mode=none
2022-03-10 14:11:55.246599 ('127.0.0.1', 2620) Reply: !mode= 0 ;
2022-03-10 14:11:55.246662 ('127.0.0.1', 2620) Qry: net_protocol=udt:4M:2M
2022-03-10 14:11:55.257122 ('127.0.0.1', 2620) Reply: !net_protocol = 0 ;
2022-03-10 14:11:55.257184 ('127.0.0.1', 2620) Qry: mtu=1500
2022-03-10 14:11:55.267638 ('127.0.0.1', 2620) Reply: !mtu= 0 ;
2022-03-10 14:11:55.267697 ('127.0.0.1', 2620) Qry: ipd=12000ns
2022-03-10 14:11:55.278155 ('127.0.0.1', 2620) Reply: !ipd=  0 ;
2022-03-10 14:11:55.278214 ('127.0.0.1', 2620) Qry: net_port=2630
2022-03-10 14:11:55.288709 ('127.0.0.1', 2620) Reply: !net_port= 0 ;
2022-03-10 14:11:55.288778 ('127.0.0.1', 2620) Qry: set_disks?
2022-03-10 14:11:55.299258 ('127.0.0.1', 2620) Reply: !set_disks?  0 : 36 : /mnt/disk0 : /mnt/disk1 : /mnt/disk10 : /mnt/disk11 : /mnt/disk12 : /mnt/disk13 : /mnt/disk14 : /mnt/disk15 : /mnt/disk16 : /mnt/disk17 : /mnt/disk18 : /mnt/disk19 : /mnt/disk2 : /mnt/disk20 : /mnt/disk21 : /mnt/disk22 : /mnt/disk23 : /mnt/disk24 : /mnt/disk25 : /mnt/disk26 : /mnt/disk27 : /mnt/disk28 : /mnt/disk29 : /mnt/disk3 : /mnt/disk30 : /mnt/disk31 : /mnt/disk32 : /mnt/disk33 : /mnt/disk34 : /mnt/disk35 : /mnt/disk4 : /mnt/disk5 : /mnt/disk6 : /mnt/disk7 : /mnt/disk8 : /mnt/disk9 ;
Traceback (most recent call last):
  File "/home/oper/jive5ab-git/scripts/m5copy", line 4667, in <module>
    with xfer_context(src, dst) as xfer:
  File "/home/oper/jive5ab-git/scripts/m5copy", line 4238, in __enter__
    self.dataSource = self.stype(self.srcLocation)
  File "/home/oper/jive5ab-git/scripts/m5copy", line 2284, in __init__
    self.pathList = set(functools.reduce(operator.add,
TypeError: can only concatenate list (not "filter") to list
oper@watt:~$
```

**Comment by haavee** [comment]
Can you update your 3.1.0-branch and try again? There were some still deeper buried "treasures" that were under the radar. Note that the `pyflakes3` tool _completely_ misses those kind of issues ... (none of the reported things turn out to be fatal ones, or even causing the script to misbehave, at least for the problems that I had overlooked in the Py2/Py3 compatibility conversion so far)

**Comment by jaatroko** [comment]
Now it seems to work, thanks. We only use m5copy of the scripts, and only for transferring single or multiple scans, with the options shown above. So I'm afraid you'll have to test the other scripts (as well as m5copy more extensively) yourself.

**Comment by haavee** [comment]
Sure - no problem! I would not expect you to test _everything_, that is well understood.
But in case you find more issues, do not hesitate to report them, thanks!
